name: Versioning

on:
  push:
    branches:
      - master

jobs:
  create_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create version tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag v${{ github.run_number }}
          git push --tags --force origin v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
